---
- name: create journald.conf.d
  file:
    path: /usr/lib/systemd/journald.conf.d
    state: directory

- name: template journald.conf override
  template:
    src: 99-retention.conf
    dest: /usr/lib/systemd/journald.conf.d/
  register: retention

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
  when: retention.changed
