---
- name: include OS-dependent variables
  include_vars:
    file: os_{{ ansible_lsb.id }}.yml

- name: install requirements for some Ansible operations
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - aptitude
    - curl
    - git
    - python-apt
    - unzip

- name: install CPU microcode updates
  apt:
    name: "{{ item.package }}"
    state: present
  when:
    - basics_microcode_updates
    - ansible_processor[0] == item.vendor
    - ansible_architecture == item.arch
  with_items:
    - { "vendor": "AuthenticAMD", "arch": "x86_64", "package": "amd64-microcode" }
    - { "vendor": "GenuineIntel", "arch": "x86_64", "package": "intel-microcode" }
