---
- name: include OS-dependent variables
  include_vars:
    file: os_{{ ansible_lsb.id }}.yml

- name: install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - cron
    - unattended-upgrades

- name: install update-notifier-common
  apt:
    name: update-notifier-common
    state: present
  when: ansible_distribution == "Ubuntu"

- name: copy 10periodic
  copy:
    src: 10periodic
    dest: /etc/apt/apt.conf.d

- name: template 50unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: check for apt-compat
  stat: path=/etc/cron.daily/apt-compat
  register: f

- name: remove systemd hack from apt-compat
  replace:
    dest: /etc/cron.daily/apt-compat
    regexp: 'if \[ -d /run/systemd/system \]; then\n.+\nfi\n'
  when: f.stat.exists

- name: disable apt-daily.timer
  command: systemctl disable apt-daily.timer
  args:
    removes: /etc/systemd/system/timers.target.wants/apt-daily.timer
