---
- name: install required packages
  apt:
    name:
      - cron
      - unattended-upgrades
    state: present

- name: install update-notifier-common
  apt:
    name: update-notifier-common
    state: present
  when: ansible_distribution == "Ubuntu"

- name: copy 10periodic
  copy:
    src: 10periodic
    dest: /etc/apt/apt.conf.d

- name: template 50unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
